
name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      SOURCE_DIR: "./"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI: false
    steps:
      - uses: actions/checkout@v3

      - uses: benjlevesque/short-sha@v1.2
      - uses: elgohr/Publish-Docker-Github-Action@master
        name: Publish to Github Packages Registry
        with:
          name: ${{ secrets.DOCKER_REPOSITORY }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          dockerfile: Dockerfile
          tags: 0.1-${{ env.SHA }}

      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/apikey.key
            chmod 600 ~/.ssh/apikey.key
            cat >>~/.ssh/config <<END
            Host apikey
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/apikey.key
              StrictHostKeyChecking no
            END
        env:
          SSH_USER: ${{ secrets.AWS_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.AWS_HOST }}

      #- name: Stop the server
      #clean docker images -> docker rmi $(docker images -a -q)
      - uses: benjlevesque/short-sha@v1.2
      - name: Deploy in Cluster
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          HTTP_HOST: ${{ secrets.HTTP_HOST }}
          APP_USER: ${{ secrets.APP_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          ssh apikey "cd /var/apps/web && docker-compose stop"
          ssh apikey "cd /var/apps/web && APP_VERSION=0.1-$SHA PORT=$PORT HOST=$HOST DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD DB_DATABASE=$DB_DATABASE HTTP_HOST=$HTTP_HOST APP_USER=$APP_USER APP_PASSWORD=$APP_PASSWORD docker-compose pull"
          ssh apikey "cd /var/apps/web && APP_VERSION=0.1-$SHA PORT=$PORT HOST=$HOST DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD DB_DATABASE=$DB_DATABASE HTTP_HOST=$HTTP_HOST APP_USER=$APP_USER APP_PASSWORD=$APP_PASSWORD docker-compose up -d"
